// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwxFpc51LOIY8nSRnO-nQr8ITy4MZ4o_M',
    appId: '1:87292835485:web:222362775be1715883c674',
    messagingSenderId: '87292835485',
    projectId: 'flowdo-fdb67',
    authDomain: 'flowdo-fdb67.firebaseapp.com',
    storageBucket: 'flowdo-fdb67.firebasestorage.app',
    measurementId: 'G-2HDS1VX4WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg7roMMIhczERTDmwGKIpQgdlCwOpNF6M',
    appId: '1:87292835485:android:80a5bd5cbc0a570783c674',
    messagingSenderId: '87292835485',
    projectId: 'flowdo-fdb67',
    storageBucket: 'flowdo-fdb67.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwO6yRvO4bw-Z86LHe3zs_N3hZa5INszI',
    appId: '1:87292835485:ios:eb2cbb311c5072d083c674',
    messagingSenderId: '87292835485',
    projectId: 'flowdo-fdb67',
    storageBucket: 'flowdo-fdb67.firebasestorage.app',
    iosClientId: '87292835485-jbj26k39poe1acir1hh8v257285t7plg.apps.googleusercontent.com',
    iosBundleId: 'com.kimata.flowdo',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwO6yRvO4bw-Z86LHe3zs_N3hZa5INszI',
    appId: '1:87292835485:ios:d21e934deb9f940f83c674',
    messagingSenderId: '87292835485',
    projectId: 'flowdo-fdb67',
    storageBucket: 'flowdo-fdb67.firebasestorage.app',
    iosBundleId: 'com.example.flowdo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwxFpc51LOIY8nSRnO-nQr8ITy4MZ4o_M',
    appId: '1:87292835485:web:d4b8c79a132d7b5a83c674',
    messagingSenderId: '87292835485',
    projectId: 'flowdo-fdb67',
    authDomain: 'flowdo-fdb67.firebaseapp.com',
    storageBucket: 'flowdo-fdb67.firebasestorage.app',
    measurementId: 'G-BE1RC5KDHR',
  );
}
