// Regenerates lib/firebase_options.dart from native Firebase config files.
//
// Usage:
//   dart run tool/generate_firebase_options.dart

import 'dart:convert';
import 'dart:io';

void main() {
  final root = Directory.current;
  if (!File('${root.path}/pubspec.yaml').existsSync()) {
    stderr.writeln('Run from the FlowDo project root.');
    exit(1);
  }

  final androidJson = jsonDecode(
    File('android/app/google-services.json').readAsStringSync(),
  ) as Map<String, dynamic>;
  final projectInfo = androidJson['project_info'] as Map<String, dynamic>;
  final androidClient = (androidJson['client'] as List).first as Map;
  final androidClientInfo = androidClient['client_info'] as Map;
  final androidApiKey =
      ((androidClient['api_key'] as List).first as Map)['current_key'] as String;

  final iosPlist = File('ios/Runner/GoogleService-Info.plist').readAsStringSync();
  String plistValue(String key) {
    final pattern = RegExp('<key>$key</key>\\s*<string>([^<]+)</string>');
    final match = pattern.firstMatch(iosPlist);
    if (match == null) {
      throw StateError('Missing $key in GoogleService-Info.plist');
    }
    return match.group(1)!;
  }

  final projectId = projectInfo['project_id'] as String;
  final storageBucket = projectInfo['storage_bucket'] as String;
  final senderId = projectInfo['project_number'] as String;

  final content = '''
// File generated by tool/generate_firebase_options.dart
// Project: $projectId
//
// Source:
//   android/app/google-services.json
//   ios/Runner/GoogleService-Info.plist

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('FlowDo は Web をサポートしていません。');
    }

    return switch (defaultTargetPlatform) {
      TargetPlatform.android => android,
      TargetPlatform.iOS => ios,
      TargetPlatform.macOS => ios,
      _ => throw UnsupportedError(
          'FlowDo は \$defaultTargetPlatform をサポートしていません。',
        ),
    };
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '$androidApiKey',
    appId: '${androidClientInfo['mobilesdk_app_id']}',
    messagingSenderId: '$senderId',
    projectId: '$projectId',
    storageBucket: '$storageBucket',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '${plistValue('API_KEY')}',
    appId: '${plistValue('GOOGLE_APP_ID')}',
    messagingSenderId: '${plistValue('GCM_SENDER_ID')}',
    projectId: '${plistValue('PROJECT_ID')}',
    storageBucket: '${plistValue('STORAGE_BUCKET')}',
    iosBundleId: '${plistValue('BUNDLE_ID')}',
  );
}
''';

  File('lib/firebase_options.dart').writeAsStringSync(content);
  stdout.writeln('Generated lib/firebase_options.dart for project $projectId');
}
